sudo: required
services:
  - docker

before_install:
  - docker build -t sanchh007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanchh007/react-test npm test

after_success:
  - docker build -t sanchh007/multi-client ./client
  - docker build -t sanchh007/multi-nginx ./nginx
  - docker build -t sanchh007/multi-server ./server
  - docker build -t sanchh007/multi-worker ./worker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push sanchh007/multi-client
  - docker push sanchh007/multi-nginx
  - docker push sanchh007/multi-server
  - docker push sanchh007/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-072934882887
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
